volumes:
  r4-database:
    name: r4-database
  postgres_data:
    name: postgres_data

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      keycloak:
        condition: service_started
      smart-launcher:
        condition: service_started
      oauth2-proxy:
        condition: service_started
    networks:
      - fhir-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    command: start-dev --import-realm --db=postgres --http-port 8180 --http-enabled=true
    depends_on:
      db:
        condition: service_started
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_BOOTSTRAP_ADMIN_USERNAME=fhir-admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=pa55word
      - KC_HOSTNAME=${PUBLIC_HOST}
      - KC_HOSTNAME_PORT=443
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db/keycloak
      - KC_DB_USERNAME=kcuser
      - KC_DB_PASSWORD=kcpassword
      - KC_HTTP_RELATIVE_PATH=/
      - KC_PROXY=edge
    volumes:
      - ./keycloak-data/fhir-realm.json:/opt/keycloak/data/import/fhir-realm.json
    networks:
      - fhir-network

  smart-launcher:
    container_name: smart-launcher
    build:
      context: ./smart-launcher-v2
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - SECRET=${LAUNCHER_SECRET}
      - PORT=80
      - HOST=0.0.0.0
      - BASE_URL=https://${PUBLIC_HOST}
      - LAUNCHER_BASE_URL=https://${PUBLIC_HOST}
      - PICKER_ORIGIN=https://${PUBLIC_HOST}/browser
      - FHIR_SERVER_R4=https://${PUBLIC_HOST}/fhir/hapi-fhir-jpaserver/fhir
      - FHIR_SERVER_R4_INTERNAL=http://r4:8080/hapi-fhir-jpaserver/fhir
      - PICKER_CONFIG_R4=r4-local
      - CONNECT_SRC=" 'self' https://${PUBLIC_HOST} https://cdn.jsdelivr.net "
    networks:
      - fhir-network

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY=true
      - OAUTH2_PROXY_PROVIDER=keycloak-oidc
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_CLIENT_ID=${CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=unused
      - OAUTH2_PROXY_REDIRECT_URL=https://${PUBLIC_HOST}/fhir/oauth2/callback
      - OAUTH2_PROXY_RELATIVE_REDIRECT_URL=true
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://keycloak:8180/realms/fhir
      
      - OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION=true
      
      - OAUTH2_PROXY_UPSTREAMS=http://r4:8080/

      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_COOKIE_SECRET=12345678901234567890123456789012

      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_SCOPE=openid email profile
      - OAUTH2_PROXY_OIDC_EMAIL_CLAIM=sub
      - OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL=true
      - OAUTH2_PROXY_CODE_CHALLENGE_METHOD=S256
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_USER_ID_CLAIM=preferred_username
    networks:
      - fhir-network
    depends_on:
      - keycloak

  r4:
    container_name: r4
    image: ${R4_IMAGE}
    environment:
      - PORT=8080
      - oidc.enabled=true
      - oidc.issuer=https://${PUBLIC_HOST}/realms/fhir
      - oidc.clientId=${CLIENT_ID}
    volumes:
      - "r4-database:/usr/local/tomcat/target/database"
    networks:
      - fhir-network

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: kcuser
      POSTGRES_PASSWORD: kcpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fhir-network

  patient-browser:
    container_name: patient-browser
    image: smartonfhir/patient-browser:latest
    volumes:
      - ./patient-browser:/usr/share/nginx/html/config
    environment:
      - HOST=${PUBLIC_HOST}
      - CONFIG_R4=r4-local
    networks:
      - fhir-network

networks:
  fhir-network:
    name: fhir-network
    external: true