worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 443 ssl;
        server_name smartonfhir.sandbox.local;

        ssl_certificate     /etc/nginx/certs/sandbox.crt;
        ssl_certificate_key /etc/nginx/certs/sandbox.key;


        location / {
            proxy_pass http://smart-launcher:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /realms/ {
            proxy_pass http://keycloak:8180/realms/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Port 443;
        }

        location /admin/ {
            proxy_pass http://keycloak:8180/admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Port 443;
        }

        location /fhir/ {
            proxy_pass http://r4:8080/; 
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Port 443;
            
            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Authorization, Content-Type, Keep-Alive, User-Agent, X-Requested-With, X-FHIR-Starter" always;
            add_header Access-Control-Expose-Headers "Content-Location, Location" always;

            if ($request_method = 'OPTIONS') {
                return 204;
            }
        }
    }
}
